### PR TITLE
add window/app pinning/unpinning shortcuts

### PR DESCRIPTION
**Pull request by mlabaj**
Hi,
I added shortcuts for window/app pinning to all desktops (already present in the DLL).

Possible use cases:
* Have video player/notes/... present on all desktops (especially useful with multiple monitors)
* Quickly move app with several windows between desktops (pin app, move to desired desktop, unpin app)

### CODE REVIEW

**Comment by sdias** [comment]
Thanks for the PR. Everything looks good, but I think a refactor of the keyboard shortcut settings is in order, since it is not easy to understand at a glance which settings are for modifiers and which are not. Are you OK with me merging this and doing a few changes afterwards?

**Comment by meffect** [comment]
nooice

**Comment by mlabaj** [comment]
@sdias Thanks, yes, go ahead. I also thought about DRYing it up a little, but didn't want to break anything :)

**Comment by sdias** [comment]
@mlabaj Thanks. I'm doing a few more changes to the settings in general, which hopefully will make them a bit more manageable.

**Comment by sdias** [comment]
@mlabaj Thanks again for this. I'm going to publish a new version in a bit with the changes. I did change the way you set the keyboard shortcuts for this though, to hopefully make it simpler and more flexible.

**Pull request merged**
