### PR TITLE
Reorg documentation

### PR DESCRIPTION
**Pull request by sdias**

### CODE REVIEW

**Comment by sdias** [comment]
@GioBonvi This looks good, I just fixed a few spelling mistakes. I think we could rework some more bits, but as a first version works great. :) There is one thing I'd like to change though, and I'm not sure if you agree: I think entire sentences in items of lists should start with upper case.

**Comment by sdias** [comment]
@GioBonvi Another thing is that I think the index file should use the current name and location of the README.md file, so that GitHub displays it properly in the homepage of the project.

**Comment by GioBonvi** [comment]
@sdias I am glad you like the idea. Sorry for the mistakes and the formatting inconsistencies: I had already done a commit after proofreading where I fixed all of this, but forgot to push it. My fault.

Regarding the naming conventions it all depends on how we decide to proceed:

- if you prefer to build a wiki then all the contents of the `/docs` folder can be deleted and moved to the wiki
- if we are going to use the GIthHub Pages alternative instead all the file should be kept where they are, but the `/docs/index.md` file should be moved to `/README.md` and all the links in it and to it should be edited (links in files inside `/docs` should point to `../README.md` and links inside `README.md` should point to `docs/SOMEFILE.md`)

**Comment by sdias** [comment]
@GioBonvi No worries. Feel free to incorporate your changes, and sorry about my commit, it was a bit presumptuous of me to just fix it like that. I would like to go with the GitHub pages alternative, it seems to be equally good, but require less work, maintenance wise.

**Comment by GioBonvi** [comment]
@sdias No problem at all: communicating over the Internet is always source of troubles, even without the language barrier we have ;)

With my last two commits the work should be finished: if you agree then we can merge to master and then you will have to activate the Pages service in the settings (as a collaborator I don't have access to them).

**Comment by sdias** [comment]
@GioBonvi The changes look good, feel free to merge to master. I'll enable Pages.

**Comment by GioBonvi** [comment]
Looks like I messed up with git somehow... I'm merging this manually

**Pull request closed without merging**
